version: '3'

services:
  url-shortener:
    build: .
    container_name: url-shortener
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      # Adicionando credenciais AWS fictícias para DynamoDB local
      - AWS_ACCESS_KEY_ID=fakeAccessKey
      - AWS_SECRET_ACCESS_KEY=fakeSecretKey
      # Garantindo que as URLs do serviço usem os nomes dos contêineres no Docker
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/urlshortener
      - REDIS_URL=redis:6379
      - AWS_ENDPOINT=http://dynamodb-local:8000
    networks:
      - monitoring
    depends_on:
      - postgres
      - redis
      - dynamodb-local
    volumes:
      - ./.env:/app/.env

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urlshortener
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring
    volumes:
      - redis-data:/data

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    depends_on:
      - url-shortener

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards/config
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:

volumes:
  grafana-data:
  postgres-data:
  redis-data:
  dynamodb-data: